### ISSUE TITLE
Node Normalizer Url

### ISSUE THREAD

**Issue by cmaceves** [TranslatorSRI/Benchmarks#27]
Hello! I've been using this tool, and last week I began to get a 500 error when running benchmark_evaluate. I traced it back through the code and realized that [this url](https://github.com/TranslatorSRI/Benchmarks/blob/87da1baffc0bd69d7a32db8a278122cb1960ae8f/benchmarks/utils/normalize.py#L7) is the culprit for the internal server error. Is there a better URL I can use to avoid this error?

**Comment by gaurav** [comment]
That URL should work! What command did you run that caused the error? Do you know which CURIEs you are trying to normalize at the time?

**Comment by cmaceves** [comment]
I was running a python script containing the lines 
`from benchmarks.eval import evaluate_results`
`results = evaluate_results("DrugCentral_creative", direct)` however I'm actually unable to replicate my initial error now.

**Comment by ngk5** [comment]
We first noticed the `500 Internal Server Error` on 9/26, and I believe there was an upgrade to Node Norm being done that day. Since the existing URL may be more unpredictable than other instances, could/should the URL be changed to prod or a different instance (eg. https://nodenorm.transltr.io/1.3/get_normalized_nodes) ?

**Comment by maximusunc** [comment]
It sounds like this error is no longer happening. Closing for now, but feel free to open back up if you see this issue again.
